In [3]:
import numpy as np

In [5]:
mylist = [1,2,3,4]
type(mylist)

list

In [8]:
myarray = np.array(mylist)
type(myarray)

numpy.ndarray

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
np.ones([5,5])
np.ones(shape=(6,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.zeros([5,5])
np.zeros(shape=(5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
type(np.zeros([4,5]))

numpy.ndarray

In [37]:
arr = np.random.randint(10,51,4)
arr

array([19, 23, 50, 14])

In [38]:
np.random.seed(101)
np.random.rand()

0.5163986277024462

In [43]:
ind_max = arr.argmax()
arr[ind_max]


50

In [54]:
arr2 = arr.reshape((2,2))
arr2.shape

(2, 2)

In [58]:
random_array = np.random.randint(0,100,25).reshape((5,5))
random_array

array([[86,  9, 45,  2, 18],
       [58, 92, 11, 10, 94],
       [35, 28,  3, 83, 84],
       [47, 14, 69, 60, 69],
       [51,  6, 88, 71, 68]])

In [61]:
random_array[2:4,2:4]

array([[ 3, 83],
       [69, 60]])